{"text": "2020-08-25 09:53:24.094 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.033000", "seconds": 0.033}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 13376, "name": "MainProcess"}, "thread": {"id": 16256, "name": "MainThread"}, "time": {"repr": "2020-08-25 09:53:24.094000+08:00", "timestamp": 1598320404.094}}}
{"text": "2020-08-25 09:53:24.094 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.033000", "seconds": 0.033}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 13376, "name": "MainProcess"}, "thread": {"id": 16256, "name": "MainThread"}, "time": {"repr": "2020-08-25 09:53:24.094000+08:00", "timestamp": 1598320404.094}}}
{"text": "2020-08-25 09:56:10.279 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.032000", "seconds": 0.032}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 13124, "name": "MainProcess"}, "thread": {"id": 1716, "name": "MainThread"}, "time": {"repr": "2020-08-25 09:56:10.279000+08:00", "timestamp": 1598320570.279}}}
{"text": "2020-08-25 09:56:10.280 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.033000", "seconds": 0.033}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 13124, "name": "MainProcess"}, "thread": {"id": 1716, "name": "MainThread"}, "time": {"repr": "2020-08-25 09:56:10.280000+08:00", "timestamp": 1598320570.28}}}
{"text": "2020-08-25 13:49:16.279 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.033000", "seconds": 0.033}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 9072, "name": "MainProcess"}, "thread": {"id": 3132, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:49:16.279000+08:00", "timestamp": 1598334556.279}}}
{"text": "2020-08-25 13:49:16.280 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.034000", "seconds": 0.034}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 9072, "name": "MainProcess"}, "thread": {"id": 3132, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:49:16.280000+08:00", "timestamp": 1598334556.28}}}
{"text": "2020-08-25 13:49:42.770 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.034000", "seconds": 0.034}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 16052, "name": "MainProcess"}, "thread": {"id": 12748, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:49:42.770000+08:00", "timestamp": 1598334582.77}}}
{"text": "2020-08-25 13:49:42.771 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.035000", "seconds": 0.035}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 16052, "name": "MainProcess"}, "thread": {"id": 12748, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:49:42.771000+08:00", "timestamp": 1598334582.771}}}
{"text": "2020-08-25 13:49:42.772 | ERROR    | __main__:<module>:60 - An error has been caught in function '<module>', process 'MainProcess' (16052), thread 'MainThread' (12748):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n                \u2514 ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000000002707D68>, origin='c:\\\\Us...\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n         \u2514 <code object <module> at 0x000000000214CDB0, file \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFile...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy\\__main__.py\", line 45, in <module>\n    cli.main()\n    \u2502   \u2514 <function main at 0x00000000039E9510>\n    \u2514 <module 'debugpy.server.cli' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\\\py...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 430, in main\n    run()\n    \u2514 <function run_file at 0x00000000039E92F0>\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 267, in run_file\n    runpy.run_path(options.target, run_name=compat.force_str(\"__main__\"))\n    \u2502     \u2502        \u2502       \u2502                \u2502      \u2514 <function force_str at 0x00000000029CE158>\n    \u2502     \u2502        \u2502       \u2502                \u2514 <module 'debugpy.common.compat' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\...\n    \u2502     \u2502        \u2502       \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502     \u2502        \u2514 <debugpy.server.cli.Options object at 0x00000000039D64E0>\n    \u2502     \u2514 <function run_path at 0x0000000002855EA0>\n    \u2514 <module 'runpy' from 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36\\\\lib\\\\runpy.py'>\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n             \u2502                     \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n             \u2514 ''\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n    \u2502         \u2502         \u2502         \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502         \u2502         \u2514 ''\n    \u2502         \u2514 None\n    \u2514 '__main__'\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\\\Users\\\\de...\n         \u2514 <code object <module> at 0x00000000039F3F60, file \"c:\\Users\\dell\\Desktop\\001.py\", line 1>\n\n> File \"c:\\Users\\dell\\Desktop\\001.py\", line 60, in <module>\n    test_catch()\n    \u2514 <function test_catch at 0x0000000003F18F28>\n\n  File \"c:\\Users\\dell\\Desktop\\001.py\", line 58, in test_catch\n    return a+b\n           \u2502 \u2514 {'\u9875\u9762\u52a0\u8f7d\u65f6': '100ms'}\n           \u2514 {'\u9875\u9762\u52a0\u8f7d\u65f6\u95f4': 33, '\u767d\u5c4f\u65f6\u95f4': 444, 'DOM\u52a0\u8f7d\u65f6\u95f4': 444444333, '\u8d44\u6e90\u52a0\u8f7d\u6700\u5927\u8017\u65f6': 44, '\u9875\u9762\u52a0\u8f7d\u65f6': '100ms'}\n\nTypeError: unsupported operand type(s) for +: 'dict' and 'dict'\n", "record": {"elapsed": {"repr": "0:00:00.036000", "seconds": 0.036}, "exception": {"type": "TypeError", "value": "unsupported operand type(s) for +: 'dict' and 'dict'", "traceback": true}, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 60, "message": "An error has been caught in function '<module>', process 'MainProcess' (16052), thread 'MainThread' (12748):", "module": "001", "name": "__main__", "process": {"id": 16052, "name": "MainProcess"}, "thread": {"id": 12748, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:49:42.772000+08:00", "timestamp": 1598334582.772}}}
{"text": "2020-08-25 13:51:33.495 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.061000", "seconds": 0.061}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 15648, "name": "MainProcess"}, "thread": {"id": 7060, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:51:33.495000+08:00", "timestamp": 1598334693.495}}}
{"text": "2020-08-25 13:51:33.496 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.062000", "seconds": 0.062}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 15648, "name": "MainProcess"}, "thread": {"id": 7060, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:51:33.496000+08:00", "timestamp": 1598334693.496}}}
{"text": "2020-08-25 13:51:33.497 | ERROR    | __main__:<module>:60 - An error has been caught in function '<module>', process 'MainProcess' (15648), thread 'MainThread' (7060):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n                \u2514 ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000000021F7D68>, origin='c:\\\\Us...\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n         \u2514 <code object <module> at 0x0000000001DFCDB0, file \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFile...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy\\__main__.py\", line 45, in <module>\n    cli.main()\n    \u2502   \u2514 <function main at 0x00000000039E9510>\n    \u2514 <module 'debugpy.server.cli' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\\\py...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 430, in main\n    run()\n    \u2514 <function run_file at 0x00000000039E92F0>\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 267, in run_file\n    runpy.run_path(options.target, run_name=compat.force_str(\"__main__\"))\n    \u2502     \u2502        \u2502       \u2502                \u2502      \u2514 <function force_str at 0x00000000029EE158>\n    \u2502     \u2502        \u2502       \u2502                \u2514 <module 'debugpy.common.compat' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\...\n    \u2502     \u2502        \u2502       \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502     \u2502        \u2514 <debugpy.server.cli.Options object at 0x00000000039D6470>\n    \u2502     \u2514 <function run_path at 0x0000000002875EA0>\n    \u2514 <module 'runpy' from 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36\\\\lib\\\\runpy.py'>\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n             \u2502                     \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n             \u2514 ''\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n    \u2502         \u2502         \u2502         \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502         \u2502         \u2514 ''\n    \u2502         \u2514 None\n    \u2514 '__main__'\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\\\Users\\\\de...\n         \u2514 <code object <module> at 0x00000000039F3F60, file \"c:\\Users\\dell\\Desktop\\001.py\", line 1>\n\n> File \"c:\\Users\\dell\\Desktop\\001.py\", line 60, in <module>\n    test_catch()\n    \u2514 <function test_catch at 0x0000000004148F28>\n\n  File \"c:\\Users\\dell\\Desktop\\001.py\", line 58, in test_catch\n    return a+b+ctt\n           \u2502 \u2514 {'\u9875\u9762\u52a0\u8f7d\u65f6': '100ms'}\n           \u2514 {'\u9875\u9762\u52a0\u8f7d\u65f6\u95f4': 33, '\u767d\u5c4f\u65f6\u95f4': 444, 'DOM\u52a0\u8f7d\u65f6\u95f4': 444444333, '\u8d44\u6e90\u52a0\u8f7d\u6700\u5927\u8017\u65f6': 44, '\u9875\u9762\u52a0\u8f7d\u65f6': '100ms'}\n\nTypeError: unsupported operand type(s) for +: 'dict' and 'dict'\n", "record": {"elapsed": {"repr": "0:00:00.063000", "seconds": 0.063}, "exception": {"type": "TypeError", "value": "unsupported operand type(s) for +: 'dict' and 'dict'", "traceback": true}, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 60, "message": "An error has been caught in function '<module>', process 'MainProcess' (15648), thread 'MainThread' (7060):", "module": "001", "name": "__main__", "process": {"id": 15648, "name": "MainProcess"}, "thread": {"id": 7060, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:51:33.497000+08:00", "timestamp": 1598334693.497}}}
{"text": "2020-08-25 13:51:49.202 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.032000", "seconds": 0.032}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 11004, "name": "MainProcess"}, "thread": {"id": 7688, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:51:49.202000+08:00", "timestamp": 1598334709.202}}}
{"text": "2020-08-25 13:51:49.203 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.033000", "seconds": 0.033}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 11004, "name": "MainProcess"}, "thread": {"id": 7688, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:51:49.203000+08:00", "timestamp": 1598334709.203}}}
{"text": "2020-08-25 13:51:49.204 | ERROR    | __main__:<module>:60 - An error has been caught in function '<module>', process 'MainProcess' (11004), thread 'MainThread' (7688):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n                \u2514 ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000000002207D68>, origin='c:\\\\Us...\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n         \u2514 <code object <module> at 0x000000000217CDB0, file \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFile...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy\\__main__.py\", line 45, in <module>\n    cli.main()\n    \u2502   \u2514 <function main at 0x00000000039E9510>\n    \u2514 <module 'debugpy.server.cli' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\\\py...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 430, in main\n    run()\n    \u2514 <function run_file at 0x00000000039E92F0>\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 267, in run_file\n    runpy.run_path(options.target, run_name=compat.force_str(\"__main__\"))\n    \u2502     \u2502        \u2502       \u2502                \u2502      \u2514 <function force_str at 0x00000000029FE158>\n    \u2502     \u2502        \u2502       \u2502                \u2514 <module 'debugpy.common.compat' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\...\n    \u2502     \u2502        \u2502       \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502     \u2502        \u2514 <debugpy.server.cli.Options object at 0x00000000039D64E0>\n    \u2502     \u2514 <function run_path at 0x0000000002885EA0>\n    \u2514 <module 'runpy' from 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36\\\\lib\\\\runpy.py'>\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n             \u2502                     \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n             \u2514 ''\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n    \u2502         \u2502         \u2502         \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502         \u2502         \u2514 ''\n    \u2502         \u2514 None\n    \u2514 '__main__'\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\\\Users\\\\de...\n         \u2514 <code object <module> at 0x00000000039F3F60, file \"c:\\Users\\dell\\Desktop\\001.py\", line 1>\n\n> File \"c:\\Users\\dell\\Desktop\\001.py\", line 60, in <module>\n    test_catch()\n    \u2514 <function test_catch at 0x0000000003F48F28>\n\n  File \"c:\\Users\\dell\\Desktop\\001.py\", line 58, in test_catch\n    return ctt\n\nNameError: name 'ctt' is not defined\n", "record": {"elapsed": {"repr": "0:00:00.034000", "seconds": 0.034}, "exception": {"type": "NameError", "value": "name 'ctt' is not defined", "traceback": true}, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 60, "message": "An error has been caught in function '<module>', process 'MainProcess' (11004), thread 'MainThread' (7688):", "module": "001", "name": "__main__", "process": {"id": 11004, "name": "MainProcess"}, "thread": {"id": 7688, "name": "MainThread"}, "time": {"repr": "2020-08-25 13:51:49.204000+08:00", "timestamp": 1598334709.204}}}
{"text": "2020-08-25 14:08:53.673 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.034000", "seconds": 0.034}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 10356, "name": "MainProcess"}, "thread": {"id": 7492, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:08:53.673000+08:00", "timestamp": 1598335733.673}}}
{"text": "2020-08-25 14:08:53.674 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.035000", "seconds": 0.035}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 10356, "name": "MainProcess"}, "thread": {"id": 7492, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:08:53.674000+08:00", "timestamp": 1598335733.674}}}
{"text": "2020-08-25 14:09:19.876 | INFO     | __main__:<module>:52 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.031000", "seconds": 0.031}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 52, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 3408, "name": "MainProcess"}, "thread": {"id": 14364, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:09:19.876000+08:00", "timestamp": 1598335759.876}}}
{"text": "2020-08-25 14:09:19.877 | INFO     | __main__:<module>:54 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.032000", "seconds": 0.032}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 3408, "name": "MainProcess"}, "thread": {"id": 14364, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:09:19.877000+08:00", "timestamp": 1598335759.877}}}
{"text": "2020-08-25 14:09:19.878 | ERROR    | __main__:<module>:60 - An error has been caught in function '<module>', process 'MainProcess' (3408), thread 'MainThread' (14364):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n                \u2514 ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000000002787D68>, origin='c:\\\\Us...\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n         \u2514 <code object <module> at 0x00000000026FCDB0, file \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFile...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy\\__main__.py\", line 45, in <module>\n    cli.main()\n    \u2502   \u2514 <function main at 0x00000000039E9510>\n    \u2514 <module 'debugpy.server.cli' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\\\py...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 430, in main\n    run()\n    \u2514 <function run_file at 0x00000000039E92F0>\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 267, in run_file\n    runpy.run_path(options.target, run_name=compat.force_str(\"__main__\"))\n    \u2502     \u2502        \u2502       \u2502                \u2502      \u2514 <function force_str at 0x0000000002A4E158>\n    \u2502     \u2502        \u2502       \u2502                \u2514 <module 'debugpy.common.compat' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\...\n    \u2502     \u2502        \u2502       \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502     \u2502        \u2514 <debugpy.server.cli.Options object at 0x00000000039D64E0>\n    \u2502     \u2514 <function run_path at 0x00000000028D5EA0>\n    \u2514 <module 'runpy' from 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36\\\\lib\\\\runpy.py'>\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n             \u2502                     \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n             \u2514 ''\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n    \u2502         \u2502         \u2502         \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502         \u2502         \u2514 ''\n    \u2502         \u2514 None\n    \u2514 '__main__'\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\\\Users\\\\de...\n         \u2514 <code object <module> at 0x00000000039F3F60, file \"c:\\Users\\dell\\Desktop\\001.py\", line 1>\n\n> File \"c:\\Users\\dell\\Desktop\\001.py\", line 60, in <module>\n    test_catch()\n    \u2514 <function test_catch at 0x0000000003F18F28>\n\n  File \"c:\\Users\\dell\\Desktop\\001.py\", line 58, in test_catch\n    return ctt\n\nNameError: name 'ctt' is not defined\n", "record": {"elapsed": {"repr": "0:00:00.033000", "seconds": 0.033}, "exception": {"type": "NameError", "value": "name 'ctt' is not defined", "traceback": true}, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 60, "message": "An error has been caught in function '<module>', process 'MainProcess' (3408), thread 'MainThread' (14364):", "module": "001", "name": "__main__", "process": {"id": 3408, "name": "MainProcess"}, "thread": {"id": 14364, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:09:19.878000+08:00", "timestamp": 1598335759.878}}}
{"text": "2020-08-25 14:09:55.462 | ERROR    | __main__:<module>:55 - An error has been caught in function '<module>', process 'MainProcess' (4544), thread 'MainThread' (8052):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n                \u2514 ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000000002207D68>, origin='c:\\\\Us...\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n         \u2514 <code object <module> at 0x0000000001DFCDB0, file \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFile...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy\\__main__.py\", line 45, in <module>\n    cli.main()\n    \u2502   \u2514 <function main at 0x00000000039E9510>\n    \u2514 <module 'debugpy.server.cli' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\\\py...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 430, in main\n    run()\n    \u2514 <function run_file at 0x00000000039E92F0>\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 267, in run_file\n    runpy.run_path(options.target, run_name=compat.force_str(\"__main__\"))\n    \u2502     \u2502        \u2502       \u2502                \u2502      \u2514 <function force_str at 0x00000000029EE158>\n    \u2502     \u2502        \u2502       \u2502                \u2514 <module 'debugpy.common.compat' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\...\n    \u2502     \u2502        \u2502       \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502     \u2502        \u2514 <debugpy.server.cli.Options object at 0x00000000039D64E0>\n    \u2502     \u2514 <function run_path at 0x0000000002255EA0>\n    \u2514 <module 'runpy' from 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36\\\\lib\\\\runpy.py'>\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n             \u2502                     \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n             \u2514 ''\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n    \u2502         \u2502         \u2502         \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502         \u2502         \u2514 ''\n    \u2502         \u2514 None\n    \u2514 '__main__'\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\\\Users\\\\de...\n         \u2514 <code object <module> at 0x0000000003A31030, file \"c:\\Users\\dell\\Desktop\\001.py\", line 1>\n\n> File \"c:\\Users\\dell\\Desktop\\001.py\", line 55, in <module>\n    test_catch()\n    \u2514 <function test_catch at 0x00000000042F9F28>\n\n  File \"c:\\Users\\dell\\Desktop\\001.py\", line 53, in test_catch\n    return ctt\n\nNameError: name 'ctt' is not defined\n", "record": {"elapsed": {"repr": "0:00:00.069000", "seconds": 0.069}, "exception": {"type": "NameError", "value": "name 'ctt' is not defined", "traceback": true}, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 55, "message": "An error has been caught in function '<module>', process 'MainProcess' (4544), thread 'MainThread' (8052):", "module": "001", "name": "__main__", "process": {"id": 4544, "name": "MainProcess"}, "thread": {"id": 8052, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:09:55.462000+08:00", "timestamp": 1598335795.462}}}
{"text": "2020-08-25 14:09:55.542 | INFO     | __main__:<module>:59 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.149000", "seconds": 0.149}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 59, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 4544, "name": "MainProcess"}, "thread": {"id": 8052, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:09:55.542000+08:00", "timestamp": 1598335795.542}}}
{"text": "2020-08-25 14:09:55.543 | INFO     | __main__:<module>:61 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.150000", "seconds": 0.15}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 61, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 4544, "name": "MainProcess"}, "thread": {"id": 8052, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:09:55.543000+08:00", "timestamp": 1598335795.543}}}
{"text": "2020-08-25 14:09:55.544 | ERROR    | __main__:<module>:67 - An error has been caught in function '<module>', process 'MainProcess' (4544), thread 'MainThread' (8052):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n                \u2514 ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000000002207D68>, origin='c:\\\\Us...\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n         \u2514 <code object <module> at 0x0000000001DFCDB0, file \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFile...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy\\__main__.py\", line 45, in <module>\n    cli.main()\n    \u2502   \u2514 <function main at 0x00000000039E9510>\n    \u2514 <module 'debugpy.server.cli' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\\\py...\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 430, in main\n    run()\n    \u2514 <function run_file at 0x00000000039E92F0>\n\n  File \"c:\\Users\\dell\\.vscode\\extensions\\ms-python.python-2020.8.103604\\pythonFiles\\lib\\python\\debugpy/..\\debugpy\\server\\cli.py\", line 267, in run_file\n    runpy.run_path(options.target, run_name=compat.force_str(\"__main__\"))\n    \u2502     \u2502        \u2502       \u2502                \u2502      \u2514 <function force_str at 0x00000000029EE158>\n    \u2502     \u2502        \u2502       \u2502                \u2514 <module 'debugpy.common.compat' from 'c:\\\\Users\\\\dell\\\\.vscode\\\\extensions\\\\ms-python.python-2020.8.103604\\\\pythonFiles\\\\lib\\...\n    \u2502     \u2502        \u2502       \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502     \u2502        \u2514 <debugpy.server.cli.Options object at 0x00000000039D64E0>\n    \u2502     \u2514 <function run_path at 0x0000000002255EA0>\n    \u2514 <module 'runpy' from 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36\\\\lib\\\\runpy.py'>\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n             \u2502                     \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n             \u2514 ''\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n    \u2502         \u2502         \u2502         \u2514 'c:\\\\Users\\\\dell\\\\Desktop\\\\001.py'\n    \u2502         \u2502         \u2514 ''\n    \u2502         \u2514 None\n    \u2514 '__main__'\n\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n         \u2502     \u2514 {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\\\Users\\\\de...\n         \u2514 <code object <module> at 0x0000000003A31030, file \"c:\\Users\\dell\\Desktop\\001.py\", line 1>\n\n> File \"c:\\Users\\dell\\Desktop\\001.py\", line 67, in <module>\n    test_catch()\n    \u2514 <function test_catch at 0x00000000043182F0>\n\n  File \"c:\\Users\\dell\\Desktop\\001.py\", line 65, in test_catch\n    return ctt\n\nNameError: name 'ctt' is not defined\n", "record": {"elapsed": {"repr": "0:00:00.151000", "seconds": 0.151}, "exception": {"type": "NameError", "value": "name 'ctt' is not defined", "traceback": true}, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 67, "message": "An error has been caught in function '<module>', process 'MainProcess' (4544), thread 'MainThread' (8052):", "module": "001", "name": "__main__", "process": {"id": 4544, "name": "MainProcess"}, "thread": {"id": 8052, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:09:55.544000+08:00", "timestamp": 1598335795.544}}}
{"text": "2020-08-25 14:14:10.975 | INFO     | __main__:<module>:54 - No matter added sinks, this message is not displayed\n", "record": {"elapsed": {"repr": "0:00:00.034000", "seconds": 0.034}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 54, "message": "No matter added sinks, this message is not displayed", "module": "001", "name": "__main__", "process": {"id": 13404, "name": "MainProcess"}, "thread": {"id": 4984, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:14:10.975000+08:00", "timestamp": 1598336050.975}}}
{"text": "2020-08-25 14:14:10.976 | INFO     | __main__:<module>:56 - This message however is propagated to the sinks\n", "record": {"elapsed": {"repr": "0:00:00.035000", "seconds": 0.035}, "exception": null, "extra": {"user": "someone"}, "file": {"name": "001.py", "path": "c:\\Users\\dell\\Desktop\\001.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 56, "message": "This message however is propagated to the sinks", "module": "001", "name": "__main__", "process": {"id": 13404, "name": "MainProcess"}, "thread": {"id": 4984, "name": "MainThread"}, "time": {"repr": "2020-08-25 14:14:10.976000+08:00", "timestamp": 1598336050.976}}}
